<?php  exit();
/*
Page: /dedecms/dede/
Error: Table 'bobo.dede_arctype' doesn't exist <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/
Error: Table 'bobo.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/
Error: Table 'bobo.dede_plus' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus` WHERE isshow=1 ORDER BY aid ASC</font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_menu.php
Error: Table 'bobo.dede_arctype' doesn't exist <br />Error sql: <font color='red'> SELECT channeltype FROM `dede_arctype` GROUP BY channeltype </font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_menu.php
Error: Table 'bobo.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id,typename,addcon,mancon FROM `dede_channeltype` WHERE id IN(1) AND id<>-1 AND isshow=1 ORDER BY id ASC</font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php
Error: Table 'bobo.dede_plus_seoinfo' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus_seoinfo` ORDER BY id DESC LIMIT 0,1;</font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php
Error: Table 'bobo.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php
Error: Table 'bobo.dede_arctiny' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_arctiny` LIMIT 0,1;</font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php
Error: Table 'bobo.dede_archives' doesn't exist <br />Error sql: <font color='red'>SELECT arc.id, arc.arcrank, arc.title, arc.channel, ch.editcon  FROM `dede_archives` arc
            LEFT JOIN `dede_channeltype` ch ON ch.id = arc.channel
             WHERE arc.arcrank<>-2 ORDER BY arc.id DESC LIMIT 0, 6 </font>
Time2016-10-27 22:03:07
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php?dopost=get_seo
Error: Table 'bobo.dede_plus_seoinfo' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_plus_seoinfo` ORDER BY id DESC LIMIT 0,1;</font>
Time2016-10-27 22:03:08
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_testenv.php
Error: Table 'bobo.dede_admin' doesn't exist <br />Error sql: <font color='red'>SELECT usertype,userid,pwd FROM dede_admin WHERE `userid`='admin' LIMIT 0,1;</font>
Time2016-10-27 22:03:16
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php?dopost=getRightSide
Error: Table 'bobo.dede_member' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member` LIMIT 0,1;</font>
Time2016-10-27 22:03:18
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php?dopost=getRightSide
Error: Table 'bobo.dede_feedback' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_feedback` LIMIT 0,1;</font>
Time2016-10-27 22:03:18
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php?dopost=getRightSide
Error: Table 'bobo.dede_channeltype' doesn't exist <br />Error sql: <font color='red'>SELECT id, typename FROM `dede_channeltype` </font>
Time2016-10-27 22:03:18
*/
?>
<?php  exit();
/*
Page: /dedecms/dede/index_body.php?dopost=getRightSide
Error: Table 'bobo.dede_arctiny' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(channel) AS dd, channel FROM `dede_arctiny` GROUP BY channel </font>
Time2016-10-27 22:03:18
*/
?>
